owner: Omikorin # Your GitHub organization or username, where this repository lives
repo: pwr-uptime # The name of this repository

sites:
  - name: Akademicki Inkubator Przedsiębiorczości
    url: https://inkubator.pwr.edu.pl
  - name: Biblioteka
    url: https://biblioteka.pwr.edu.pl
  - name: Biuletyn Informacji Publicznej
    url: https://bip.pwr.edu.pl
  - name: Biuro Karier
    url: https://biurokarier.pwr.edu.pl
  - name: Doktoranci
    url: https://doktoranci.pwr.edu.pl
  - name: Edukacja.CL
    url: https://edukacja.pwr.wroc.pl
  - name: Elektroniczna Karta Pracownicza
    url: https://ekp.pwr.edu.pl
  - name: Elektroniczna Książka Telefoniczna
    url: https://ekt.pwr.edu.pl
  - name: Elektroniczny Monitoring Umów 
    url: https://emu.pwr.edu.pl
  - name: ePortal
    url: https://eportal.pwr.edu.pl
  - name: JSOS
    url: https://jsos.pwr.edu.pl
  - name: Oferty Pracy
    url: https://ofertypracy.pwr.edu.pl
  - name: Pion Prorektora ds. Studenckich
    url: https://prs.pwr.edu.pl
  - name: Poczta Pracownicza (przestarzała)
    url: https://e.pwr.edu.pl/
  - name: Poczta Pracownicza (przestarzała, nie działa)
    url: https://pmail.pwr.edu.pl
  - name: Poczta Studencka (przestarzała, nie działa)
    url: https://s.student.pwr.edu.pl
  - name: Poczta WCSS
    url: https://poczta.wcss.pl
  - name: Politechnika Wrocławska
    url: https://pwr.edu.pl
  - name: Poradnia Psychologiczna
    url: https://ppp.pwr.edu.pl
  - name: Rekrutacja
    url: https://rekrutacja.pwr.edu.pl
  - name: Samorząd Studencki
    url: https://samorzad.pwr.edu.pl
  - name: Studium Języków Obcych
    url: https://sjo.pwr.edu.pl
  - name: USOS
    url: https://web.usos.pwr.edu.pl
  - name: Zintegrowany System Kontroli Dostępu i Bezpieczeństwa Fizycznego
    url: https://skd.pwr.edu.pl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.pwr.omikor.in
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Z racji, że strony uczelni często przestają działać w dowolnym momencie, powstał monitoring stanu poniższych serwisów Politechniki Wrocławskiej.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
